services:
  # API Service - Using External Database
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web3-crowdfunding-api
    ports:
      - "3001:3001"
    # env_file:
    #   - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      MIGRATE_ON_START: ${MIGRATE_ON_START}
      SERVER_PORT: 
    restart: unless-stopped
    networks:
      - main_net

networks:
  main_net:
    external: true
