services:
  # API Service - Using External Database
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web3-crowdfunding-api
    ports:
      - "3000:3000"
    # env_file:
    #   - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      SERVER_PORT: 
    restart: unless-stopped
    networks:
      - web3-network

networks:
  web3-network:
    driver: bridge
